### ISSUE TITLE
HTML片段未闭合是基于怎样的考虑？

### ISSUE THREAD

**Issue by alvinhui** [maxlee/Smart-Snippets#1]
今天安装了LEGO，使用html代码片段的时候发现`body`和`html`标签未闭合。想请问这是一个怎样的考虑？

see: https://raw.github.com/maxlee/LEGO-Snippets/master/_/html.sublime-snippet

**Comment by maxlee** [comment]
doctype声明为html5是允许这两个标签不需要闭合，是符合html规范的；关于这个问题可以查看Google官方文档：https://developers.google.com/speed/articles/optimizing-html

**Comment by alvinhui** [comment]
标准是一个方面但是各个浏览器对标准的实现如何？尤其是猪队友ie 6 7。（先留此坑待做考究）

我还看到了这句

```
For example, if you have a list of items marked up as <li>List item</li>, you could instead just write <li>List item. 
```

平时你的团队会采用这种方式吗？
